load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

filegroup(
    name = "carla_not_in_registry_srcs",
    srcs = glob(
        ["**"],
        exclude = ["boost*/**"],
    ),
    visibility = ["//visibility:public"],
)

cmake(
    name = "carla_not_in_registry",
    cache_entries = {
        "DLAUNCH_ARGS='-prefernvidia'",
        "DCMAKE_BUILD_TYPE=Release",
        "DENABLE_ROS2=OFF",
        "DPython_ROOT_DIR=
    }
)